Internal data
* BFD-discriminator (construct time)
* isUp (construct time)

Input signals
* port-up
* port-down
* bisl-up [ISL-FSM]
* FL-ok
* FL-fail
* FL-timeout
* isl-move [ISL-FSM]

Ouput signals
* bfd-up
* bfd-down

@startuml
title BFD port FSM

state initChoice <<choice>>
[*] --> initChoice

initChoice --> IDLE : [BFD-discriminator is empty]
initChoice --> CLEANUP : [BFD-discriminator is set]

IDLE --> INSTALLING : bisl-up
IDLE -l-> FAIL : port-up

INSTALLING --> UP : port-up
INSTALLING --> CLEANUP : FL-fail
INSTALLING --> CLEANUP : isl-move
INSTALLING : enter / allocate BFD-discriminator
INSTALLING : enter / emit FL-BFD-producer setup

state cleanupChoice <<choice>>

CLEANUP --> cleanupChoice : FL-ok / release BFD-discriminator
CLEANUP --> FAIL : FL-fail
CLEANUP --> FAIL : FL-timeout
CLEANUP : enter / emit FL-BFD-producer remove
CLEANUP : port-up / set isUp = true ???
CLEANUP : port-down / set isUp = false

cleanupChoice --> IDLE : [not isUp]
cleanupChoice --> WAIT_RELEASE : [isUp]

WAIT_RELEASE --> IDLE : port-down

UP --> DOWN : port-down
UP --> CLEANUP : isl-move
UP : enter / emit bfd-up

DOWN --> UP : port-up
DOWN --> CLEANUP : isl-move
DOWN : enter / emit bfd-down

FAIL -r-> IDLE : port-down


@enduml
